// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqdqadcobqpzpveawzni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xZHFhZGNvYnFwenB2ZWF3em5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMzk1NjQsImV4cCI6MjA2ODkxNTU2NH0.Zro0xpJo4k7c0KZrhe383Yd3-9YB5K4IpKxQiQV6w3o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});